Added Notebook created by Jerom
eWaterCycle/notebooks pull request #13
Opened 2019-03-19 12:20 UTC by jeromaerts

lorentz workshop comparison file

2019-03-19 12:26 UTC, nielsdrost commented
He @sverhoeven could you have a look?

2019-03-19 12:29 UTC, nielsdrost commented on Lorentz_model_comparison.ipynb
> +    "%time pcrg.initialize(\"pcrg_rhinemeuse.ini\")"
We should insert usage of parameter db here. Manually added it, works.

2019-03-19 12:29 UTC, nielsdrost commented on Lorentz_model_comparison.ipynb
> +    "import hydrostats.data as hd\n",
Hydrostats not available in lab environment

2019-03-19 12:29 UTC, nielsdrost commented on Lorentz_model_comparison.ipynb
> +      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAsQAAAGoCAYAAABBi/M/AAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEgAACxIB0t1+/AAAADl0RVh0U29mdHdhcmUAbWF0cGxvdGxpYiB2ZXJzaW9uIDIuMi4zLCBodHRwOi8vbWF0cGxvdGxpYi5vcmc
Should be Python 3

2019-03-20 12:54 UTC, sverhoeven requested changes

2019-03-20 12:54 UTC, sverhoeven commented on Lorentz_model_comparison.ipynb
> +    "client = docker.from_env()"
Please remove cell as client var is not used in notebook.

2019-03-20 12:54 UTC, sverhoeven commented on Lorentz_model_comparison.ipynb
> +    "import hydrostats.data as hd\n",
It is now available in the lab environment, but the import is not used anywhere. 
The import should be removed or be used.

2019-03-20 12:54 UTC, sverhoeven commented on Lorentz_model_comparison.ipynb
> +    "%time pcrg.initialize(\"pcrg_rhinemeuse.ini\")"
Agree, otherwise we are unable to run it.

2019-03-20 12:54 UTC, sverhoeven commented on Lorentz_model_comparison.ipynb
> +    "obs = dataframe_from_stationId('./validation/', 6435060)\n",
Similar as model config+dataset, the validation file appears out of nowhere. Please provide instructions how to get it.

2019-03-28 10:27 UTC, sverhoeven approved these changes

2019-03-28 10:27 UTC, merged